source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/xim9160/XIMSpecs.git'

use_frameworks!

platform :ios, '8.0'

target 'XIMOneControllerKit_Example' do
  pod 'XIMOneControllerKit', :path => '../'
  pod 'CTMediator'
  target 'XIMOneControllerKit_Tests' do
    inherit! :search_paths

    
  end
end
