use_frameworks!

platform :ios, '8.0'

target 'XIMOneControllerKit_Example' do
  pod 'XIMOneControllerKit', :path => '../'

  target 'XIMOneControllerKit_Tests' do
    inherit! :search_paths

    
  end
end
